/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package licensetestapp;

import gns.license.keys.LicenseKeys;
import gns.license.manager.LicenseManager;
import gns.license.software.SoftwareLicenseManager;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rahman Md Redwanur <r.rahman@gne-it.com>
 */
public class GenerateClientInfo extends javax.swing.JFrame {

    /**
     * Creates new form GenerateClientInfo
     */
    
    private LicenseKeys lk;
    public GenerateClientInfo(LicenseKeys lk) {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        setLocation( x, y);
        setResizable(false);
        setBounds(x, y, w, h);
        
        this.lk = lk;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfProductKey = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbtnGenerate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(licensetestapp.LicenseTestApp.class).getContext().getResourceMap(GenerateClientInfo.class);
        jtfProductKey.setFont(resourceMap.getFont("jtfProductKey.font")); // NOI18N
        jtfProductKey.setText(resourceMap.getString("jtfProductKey.text")); // NOI18N
        jtfProductKey.setName("jtfProductKey"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jbtnGenerate.setFont(resourceMap.getFont("jbtnGenerate.font")); // NOI18N
        jbtnGenerate.setText(resourceMap.getString("jbtnGenerate.text")); // NOI18N
        jbtnGenerate.setName("jbtnGenerate"); // NOI18N
        jbtnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenerateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfProductKey)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(jbtnGenerate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfProductKey, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenerateActionPerformed
        try {
            String productkey = jtfProductKey.getText();
            if(productkey.isEmpty()) throw new Exception("Product key is empty");
            String path = SoftwareLicenseManager.getSavingPath(this, "", "", "gns");
            if(path.isEmpty()) throw new Exception("License saving path is empty");
            SoftwareLicenseManager.writeClientInfo(path, productkey, lk);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jbtnGenerateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnGenerate;
    private javax.swing.JTextField jtfProductKey;
    // End of variables declaration//GEN-END:variables
}
